"""job_posting tablename to jobposting

Revision ID: 2bf2bab3c89d
Revises: 30856f7fd091
Create Date: 2021-02-25 16:46:13.943305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf2bab3c89d'
down_revision = '30856f7fd091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobposting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=32), nullable=True),
    sa.Column('location_city', sa.String(length=32), nullable=True),
    sa.Column('location_state', sa.String(length=5), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('position', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('job_posting')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_posting',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('company', sa.VARCHAR(length=32), nullable=True),
    sa.Column('location_city', sa.VARCHAR(length=32), nullable=True),
    sa.Column('location_state', sa.VARCHAR(length=5), nullable=True),
    sa.Column('updated', sa.DATETIME(), nullable=True),
    sa.Column('position', sa.VARCHAR(length=32), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('status IN (0, 1)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('jobposting')
    # ### end Alembic commands ###
