"""jobpostings table

Revision ID: 30856f7fd091
Revises: 
Create Date: 2021-02-25 16:42:49.484344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30856f7fd091'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_posting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=32), nullable=True),
    sa.Column('location_city', sa.String(length=32), nullable=True),
    sa.Column('location_state', sa.String(length=5), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('position', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_posting')
    # ### end Alembic commands ###
