"""notes column for jobposting

Revision ID: 696c5456afb5
Revises: a22f3423d892
Create Date: 2021-03-08 20:58:32.445080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696c5456afb5'
down_revision = 'a22f3423d892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobposting', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobposting', 'notes')
    # ### end Alembic commands ###
