"""filepath for resume and coverletter

Revision ID: a22f3423d892
Revises: c8397c44c2d9
Create Date: 2021-02-27 15:20:06.776229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a22f3423d892'
down_revision = 'c8397c44c2d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coverletter', sa.Column('filepath', sa.String(), nullable=True))
    op.add_column('resume', sa.Column('filepath', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'filepath')
    op.drop_column('coverletter', 'filepath')
    # ### end Alembic commands ###
