"""resume and coverletter tables

Revision ID: c8397c44c2d9
Revises: 2bf2bab3c89d
Create Date: 2021-02-25 17:14:46.334418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8397c44c2d9'
down_revision = '2bf2bab3c89d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coverletter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('jobposting_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jobposting_id'], ['jobposting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('jobposting_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jobposting_id'], ['jobposting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume')
    op.drop_table('coverletter')
    # ### end Alembic commands ###
